package GUIs;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */

import Admin.BackEnd;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.awt.Rectangle;
import java.util.Scanner;
import javax.imageio.ImageIO;
import main.Game;

/**
 *
 * @author User
 */
public class NewUserInfo extends javax.swing.JFrame {

    /**
     * Creates new form NewUserInfo
     */
    public NewUserInfo() {
        initComponents();
        
        BackEnd be = new BackEnd();
        String line = be.newUserLogin();
        Scanner scLine = new Scanner (line).useDelimiter("#");
        lblUsername.setText(scLine.next());
        lblPassword.setText(scLine.next());
        
    }
    
    
    

    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinimise = new javax.swing.JButton();
        lblScreenshot = new javax.swing.JLabel();
        btnScreenshot = new javax.swing.JButton();
        lblErrorScreenshot = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        lblUsernameHeading = new javax.swing.JLabel();
        lblPasswordHeading = new javax.swing.JLabel();
        spInstructions = new javax.swing.JScrollPane();
        txtInstructions = new javax.swing.JTextArea();
        lblTorch1 = new javax.swing.JLabel();
        lblTorch2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimise.setBackground(new java.awt.Color(153, 153, 153));
        btnMinimise.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMinimise.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimise.setText("―");
        btnMinimise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimiseActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimise, new org.netbeans.lib.awtextra.AbsoluteConstraints(1245, 11, -1, -1));

        lblScreenshot.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        lblScreenshot.setText("SCREENSHOT YOUR DETAILS --->");
        getContentPane().add(lblScreenshot, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 518, -1, 30));

        btnScreenshot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/screenshot.png"))); // NOI18N
        btnScreenshot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnScreenshot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScreenshotActionPerformed(evt);
            }
        });
        getContentPane().add(btnScreenshot, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 501, -1, -1));
        getContentPane().add(lblErrorScreenshot, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 470, 177, 30));

        lblHeading.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(221, 178, 45));
        lblHeading.setText("WELCOME TO THE CREW MATEY");
        getContentPane().add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 69, 713, -1));

        lblUsernameHeading.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblUsernameHeading.setForeground(new java.awt.Color(221, 178, 45));
        lblUsernameHeading.setText("New Username:");
        getContentPane().add(lblUsernameHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 183, -1, -1));

        lblPasswordHeading.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblPasswordHeading.setForeground(new java.awt.Color(221, 178, 45));
        lblPasswordHeading.setText("New Password:");
        getContentPane().add(lblPasswordHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 183, -1, -1));

        txtInstructions.setBackground(new java.awt.Color(153, 204, 255));
        txtInstructions.setColumns(20);
        txtInstructions.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txtInstructions.setRows(5);
        txtInstructions.setText("IF YOU CANNOT SEE YOUR SCREENSHOT: \n\n1. Open files and search for \"DioTreasureSignIn.png\" in the \"Search quick access\"\n   bar.\n2. Once you have found it, move it to a folder that you will remember your login\n   details. (e.g. Screenshot files)");
        txtInstructions.setAutoscrolls(false);
        txtInstructions.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtInstructions.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtInstructions.setEnabled(false);
        spInstructions.setViewportView(txtInstructions);

        getContentPane().add(spInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 308, 670, 144));
        getContentPane().add(lblTorch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 60, 50));
        getContentPane().add(lblTorch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 60, 50));

        lblUsername.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 180, 30));

        lblPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 180, 30));

        lblBG.setIcon(new javax.swing.ImageIcon("D:\\PAT - Copy\\Game Resources\\black-planet-surface-1920.jpg")); // NOI18N
        getContentPane().add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimiseActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(NewUserInfo.ICONIFIED);
    }//GEN-LAST:event_btnMinimiseActionPerformed

    private void btnScreenshotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScreenshotActionPerformed
        // TODO add your handling code here:
        //Takes screenshot

        try{
            Robot robot = new Robot();
            Rectangle rect = new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
            BufferedImage image = robot.createScreenCapture(rect);
            ImageIO.write(image, "png", new File("DioTreasureSignIn.png"));

            new Game();
            
            dispose();
        }
        catch(Exception e){
            lblErrorScreenshot.setText("Error -- Screenshot not taken");
        }

    }//GEN-LAST:event_btnScreenshotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinimise;
    private javax.swing.JButton btnScreenshot;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblErrorScreenshot;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordHeading;
    private javax.swing.JLabel lblScreenshot;
    private javax.swing.JLabel lblTorch1;
    private javax.swing.JLabel lblTorch2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsernameHeading;
    private javax.swing.JScrollPane spInstructions;
    private javax.swing.JTextArea txtInstructions;
    // End of variables declaration//GEN-END:variables
}
