package GUIs;

import Admin.BackEnd;
import Admin.Connector;
import Admin.UserScores;
import java.io.File;
import java.util.*;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        BackEnd be = new BackEnd();
        be.profileLbls(lblActualName, lblActualSurname, lblActualGrade, lblActualDOB);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnMinimise = new javax.swing.JButton();
        lblProfile = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblActualName = new javax.swing.JLabel();
        lblActualSurname = new javax.swing.JLabel();
        lblActualGrade = new javax.swing.JLabel();
        lblActualDOB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblOverallHighScores = new javax.swing.JTable();
        lblChooseLevel = new javax.swing.JLabel();
        lblOverallHighScores = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblUserHighScores = new javax.swing.JTable();
        lblUserHighScores = new javax.swing.JLabel();
        btnAddition = new javax.swing.JButton();
        btnSubtraction = new javax.swing.JButton();
        btnMultiplication = new javax.swing.JButton();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("←");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnMinimise.setBackground(new java.awt.Color(153, 153, 153));
        btnMinimise.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMinimise.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimise.setText("―");
        btnMinimise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimiseActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimise, new org.netbeans.lib.awtextra.AbsoluteConstraints(1245, 11, -1, -1));

        lblProfile.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(221, 178, 45));
        lblProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfile.setText("Profile");
        lblProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 73, -1, 50));

        lblName.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(221, 178, 45));
        lblName.setText("Name:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 123, 25));

        lblSurname.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblSurname.setForeground(new java.awt.Color(221, 178, 45));
        lblSurname.setText("Surname:");
        getContentPane().add(lblSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 123, 25));

        lblGrade.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblGrade.setForeground(new java.awt.Color(221, 178, 45));
        lblGrade.setText("Grade:");
        getContentPane().add(lblGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 123, 25));

        lblDOB.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(221, 178, 45));
        lblDOB.setText("Date of birth:");
        getContentPane().add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 180, 25));

        lblActualName.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblActualName.setForeground(new java.awt.Color(221, 178, 45));
        getContentPane().add(lblActualName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 220, 25));

        lblActualSurname.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblActualSurname.setForeground(new java.awt.Color(221, 178, 45));
        getContentPane().add(lblActualSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 240, 25));

        lblActualGrade.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblActualGrade.setForeground(new java.awt.Color(221, 178, 45));
        getContentPane().add(lblActualGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 210, 25));

        lblActualDOB.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblActualDOB.setForeground(new java.awt.Color(221, 178, 45));
        getContentPane().add(lblActualDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 220, 25));

        jtblOverallHighScores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 178, 45), 1, true));
        jtblOverallHighScores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "DatePlayed", "LevelType", "Score"
            }
        ));
        jtblOverallHighScores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtblOverallHighScores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 430, 110));

        lblChooseLevel.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblChooseLevel.setForeground(new java.awt.Color(221, 178, 45));
        lblChooseLevel.setText("Choose a Level:");
        getContentPane().add(lblChooseLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 220, 25));

        lblOverallHighScores.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblOverallHighScores.setForeground(new java.awt.Color(221, 178, 45));
        lblOverallHighScores.setText("overall high scores:");
        lblOverallHighScores.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 178, 45)));
        getContentPane().add(lblOverallHighScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 270, 30));

        jtblUserHighScores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(221, 178, 45)));
        jtblUserHighScores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "DatePlayed", "LevelType", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtblUserHighScores.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtblUserHighScores);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 420, 110));

        lblUserHighScores.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblUserHighScores.setForeground(new java.awt.Color(221, 178, 45));
        lblUserHighScores.setText("My high scores:");
        lblUserHighScores.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 178, 45)));
        getContentPane().add(lblUserHighScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 200, 30));

        btnAddition.setBackground(new java.awt.Color(204, 204, 204));
        btnAddition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddition.setText("Addition");
        btnAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdditionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddition, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, -1, -1));

        btnSubtraction.setBackground(new java.awt.Color(204, 204, 204));
        btnSubtraction.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSubtraction.setText("Subtraction");
        btnSubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractionActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtraction, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, -1, -1));

        btnMultiplication.setBackground(new java.awt.Color(204, 204, 204));
        btnMultiplication.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMultiplication.setText("Multiplication");
        btnMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicationActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 160, -1, -1));

        lblBG.setIcon(new javax.swing.ImageIcon("D:\\PAT - Copy\\Game Resources\\black-planet-surface-1920.jpg")); // NOI18N
        getContentPane().add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //Back to main menu
        
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMinimiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimiseActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(Profile.ICONIFIED);
    }//GEN-LAST:event_btnMinimiseActionPerformed

    private void btnAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdditionActionPerformed
        UserScores scores = new UserScores();
        scores.insertAdditionScores(jtblUserHighScores, jtblOverallHighScores);
        
    }//GEN-LAST:event_btnAdditionActionPerformed

    private void btnSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractionActionPerformed
        UserScores scores = new UserScores();
        scores.insertSubtractionScores(jtblUserHighScores, jtblOverallHighScores);
    }//GEN-LAST:event_btnSubtractionActionPerformed

    private void btnMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicationActionPerformed
       UserScores scores = new UserScores();
       scores.insertMultiplicationScores(jtblUserHighScores, jtblOverallHighScores);
    }//GEN-LAST:event_btnMultiplicationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddition;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMinimise;
    private javax.swing.JButton btnMultiplication;
    private javax.swing.JButton btnSubtraction;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtblOverallHighScores;
    private javax.swing.JTable jtblUserHighScores;
    private javax.swing.JLabel lblActualDOB;
    private javax.swing.JLabel lblActualGrade;
    private javax.swing.JLabel lblActualName;
    private javax.swing.JLabel lblActualSurname;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblChooseLevel;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOverallHighScores;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblUserHighScores;
    // End of variables declaration//GEN-END:variables
}
