package GUIs;



import Admin.DataValidation;
import Admin.UserArray;
import Admin.User;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class SignUp extends javax.swing.JFrame{

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        lblNameError.setVisible(false);
        lblSurnameError.setVisible(false);
        lblGradeError.setVisible(false);
        lblDOBError.setVisible(false);
        lblExistingUser.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnMinimise = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        cmbGrade = new javax.swing.JComboBox<>();
        btnSignUpVerification = new javax.swing.JButton();
        lblNameError = new javax.swing.JLabel();
        lblSurnameError = new javax.swing.JLabel();
        lblGradeError = new javax.swing.JLabel();
        lblDOBError = new javax.swing.JLabel();
        dtcDOB = new com.toedter.calendar.JDateChooser();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        lblExistingUser = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("←");
        btnBack.setAlignmentY(0.0F);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnMinimise.setBackground(new java.awt.Color(153, 153, 153));
        btnMinimise.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMinimise.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimise.setText("―");
        btnMinimise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimiseActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimise, new org.netbeans.lib.awtextra.AbsoluteConstraints(1245, 11, -1, -1));

        lblHeader.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(221, 178, 45));
        lblHeader.setText("JOIN CAPTAIN DIO'S CREW");
        getContentPane().add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 73, 394, 50));

        lblName.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(221, 178, 45));
        lblName.setText("Enter your name:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 168, 267, 32));

        lblSurname.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblSurname.setForeground(new java.awt.Color(221, 178, 45));
        lblSurname.setText("Enter your surname:");
        getContentPane().add(lblSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 227, 267, 32));

        lblDOB.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(221, 178, 45));
        lblDOB.setText("Choose your date of birth:");
        getContentPane().add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 285, -1, 32));

        lblGrade.setFont(new java.awt.Font("Castellar", 1, 14)); // NOI18N
        lblGrade.setForeground(new java.awt.Color(221, 178, 45));
        lblGrade.setText("Select your grade:");
        getContentPane().add(lblGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 351, 267, 32));

        cmbGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "6", "7", "8", "9" }));
        getContentPane().add(cmbGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 353, 90, 30));

        btnSignUpVerification.setBackground(new java.awt.Color(153, 204, 255));
        btnSignUpVerification.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnSignUpVerification.setText("Sign Up");
        btnSignUpVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpVerificationActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignUpVerification, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 464, 101, 51));

        lblNameError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblNameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 180, 301, 20));

        lblSurnameError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblSurnameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 239, 301, 20));

        lblGradeError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblGradeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 351, 301, 22));

        lblDOBError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblDOBError, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 297, 301, 20));
        getContentPane().add(dtcDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 297, 203, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 175, 203, -1));
        getContentPane().add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 234, 203, -1));

        lblExistingUser.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblExistingUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 210, 20));

        lblBG.setIcon(new javax.swing.ImageIcon("D:\\PAT - Copy\\Game Resources\\black-planet-surface-1920.jpg")); // NOI18N
        getContentPane().add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //Back to welcome page
        WelcomePage wp = new WelcomePage();
        wp.show();
        
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMinimiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimiseActionPerformed
        // TODO add your handling code here:
        //Minimise page
        this.setExtendedState(SignUp.ICONIFIED);
    }//GEN-LAST:event_btnMinimiseActionPerformed

    private void btnSignUpVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpVerificationActionPerformed
        // TODO add your handling code here:
        
        DataValidation dv = new DataValidation();
        dv.presenceCheckName(txtName, lblNameError);
        dv.presenceCheckSurname(txtSurname, lblSurnameError);
        dv.presenceCheckGrade(cmbGrade, lblGradeError);
        dv.checkDOB(lblDOBError, cmbGrade, dtcDOB);
        dv.lengthCheckSurname(txtSurname, lblSurnameError);
        dv.lengthCheckName(txtName, lblNameError);
        dv.typeCheckName(txtName, lblNameError);
        dv.typeCheckSurname(txtSurname, lblSurnameError);
        
        
        UserArray arr = new UserArray();
        if(arr.existingUser(dv.getName(), dv.getSurname(), dv.getGrade(), dv.getDOB()) == true){
            lblExistingUser.setText(dv.existingUserLbl());
            lblExistingUser.setVisible(true);
        }else if(dv.validate(lblNameError, lblSurnameError, lblGradeError, lblDOBError, lblExistingUser)){
            
             User u = new User(dv.getName(), dv.getSurname(), dv.getGrade(), dv.getDOB());
             u.insertLoginDetailsRS();
             u.insertUserInfoRS();
             
             NewUserInfo nui = new NewUserInfo();
             nui.show();
             
             dispose();
        }
        
    }//GEN-LAST:event_btnSignUpVerificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMinimise;
    private javax.swing.JButton btnSignUpVerification;
    private javax.swing.JComboBox<String> cmbGrade;
    private com.toedter.calendar.JDateChooser dtcDOB;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOBError;
    private javax.swing.JLabel lblExistingUser;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblGradeError;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblSurnameError;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
